stages:
  download:
    cmd: bash src/prepare_emails.sh
    deps:
      - code/convert_to_parquet.py
    outs:
      - data/enron_emails.parquet
  report:
    cmd: bash -c "cd report && latexmk article.tex -pdf"
    deps:
      - report/article.tex
    outs:
      - report/article.pdf
