stages:
  prepare_emails:
    cmd: bash src/prepare_emails.sh
    deps:
      - code/convert_to_parquet.py
    outs:
      - data/enron_emails.parquet
  scrape_convictions:
    cmd: python code/scrape_conviction_data.py --output data/convictions.csv
    deps:
      - code/scrape_conviction_data.py
    outs:
      - data/convictions.csv
  parse_messages:
    cmd: python code/parse_messages.py --emails_file data/enron_emails.parquet --person_yaml data/person_info.yaml --output data/processed_emails.csv
    deps:
      - code/parse_messages.py
      - data/enron_emails.parquet
      - data/person_info.yaml
    outs:
      - data/processed_emails.csv
  report:
    cmd: bash -c "cd report && latexmk article.tex -pdf"
    deps:
      - report/article.tex
    outs:
      - report/article.pdf
