stages:
  download:
    cmd: wget https://www.cs.cmu.edu/~enron/enron_mail_20150507.tar.gz -O data/enron_mail_20150507.tar.gz
    outs:
      - data/enron_mail_20150507.tar.gz
  unzip:
    cmd: tar -xf data/enron_mail_20150507.tar.gz -C data/
    deps:
      - data/enron_mail_20150507.tar.gz
    outs:
      - data/maildir
  report:
    cmd: bash -c "cd report && latexmk article.tex -pdf"
    deps:
      - report/article.tex
    outs:
      - report/article.pdf
