stages:
  prepare_emails:
    cmd: bash src/prepare_emails.sh
    deps:
      - code/convert_to_parquet.py
    outs:
      - data/enron_emails.parquet
  scrape_convictions:
    cmd: python code/scrape_conviction_data.py --output data/convictions.csv
    deps:
      - code/scrape_conviction_data.py
    outs:
      - data/convictions.csv
  parse_messages:
    cmd: python code/parse_messages.py --emails_file data/enron_emails.parquet --person_yaml data/person_info.yaml --output_dir data
    deps:
      - code/parse_messages.py
      - data/enron_emails.parquet
      - data/person_info.yaml
    outs:
      - data/norm_emails.csv
      - data/exec_emails.csv
      - data/poi_emails.csv
  mask_datasets:
    cmd: python code/mask_datasets.py
    deps:
      - code/mask_datasets.py
      - data/norm_emails.csv
      - data/exec_emails.csv
      - data/poi_emails.csv
    outs:
      - data/norm_masked_emails.csv
      - data/exec_masked_emails.csv
      - data/poi_masked_emails.csv
  dataset_splitting:
    cmd: python code/dataset_splitting.py --poi_file data/poi_masked_emails.csv --exec_file data/exec_masked_emails.csv --norm_file data/norm_masked_emails.csv --output_dir data
    deps:
      - code/dataset_splitting.py
      - data/poi_masked_emails.csv
      - data/exec_masked_emails.csv
      - data/norm_masked_emails.csv
    outs:
      - data/train_set.csv
      - data/valid_set.csv
      - data/test_set.csv
  modelling:
    cmd: mkdir -p data/model_runs && python code/modelling.py --train_file data/train_set.csv --valid_file data/valid_set.csv --test_file data/test_set.csv
    deps:
      - data/train_set.csv
      - data/valid_set.csv
      - data/test_set.csv
    outs:
      - data/experiment_data.csv
      - data/model_runs
  report:
    cmd: bash -c "cd report && latexmk article.tex -pdf"
    deps:
      - report/article.tex
    outs:
      - report/article.pdf
